export enum ComplaintsType {
  COGNITIVE_ASPECT = 'ASPECTO_COGNITIVO',
  AFFECTIVE_ASPECT = 'ASPECTO_AFECTIVO',
  BEHAVORIAL_ASPECT = 'ASPECTO_CONDUCTUAL',
  PHYSIOLOGICAL_ASPECT = 'ASPECTO_FISIOLOGICO',
  RELATIONAL_ASPECT = 'ASPECTO_RELACIONAL',
  CONTEXTUAL_ASPECT = 'ASPECTO_CONTEXTUAL',
}